name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 15
      matrix:
        php:
          - version: 7.1.3
            file: 56

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@1.3.7
      with:
       php-version: ${{ matrix.php.version }}
       extension-csv: mbstring
    - name: Install composer dependencies
      run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

