name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install PHP
      uses: shivammathur/setup-php@master
      with:
       php-version: 7.1
       extension-csv: mbstring
    - name: check php version
      run: php -v
    - name: check composer version
      run: composer -v

